version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - mynetwork

  web:
    build: ./emotiontracking
    command:
      - bash
      - -c
      - |
        python manage.py makemigrations
        python manage.py migrate
        python ./src/postgre_patient_import.py
        python ./src/elastic_mapping_import.py 
        gunicorn emotiontracking.wsgi:application --bind 0.0.0.0:8000 
  #python manage.py runserver 0.0.0.0:8000
        
    volumes:
      - ./emotiontracking:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - elasticsearch
    networks:
      - mynetwork

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - mynetwork

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    environment:
      - discovery.type=single-node
    volumes:
       - ./data/elasticsearch_data:/usr/share/elasticsearch/data/nodes
    ports:
      - "9200:9200"
    networks:
      - mynetwork

  nginx:
    build: ./nginx
    container_name: test_deploy_nginx
    ports:
      - 8008:80
    depends_on:
      - web
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

