# Generated by Django 4.2.3 on 2023-07-09 14:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0004_alter_patient_followed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='date_inscription',
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_of_registration',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
