# Generated by Django 4.2.3 on 2023-07-11 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0008_alter_patient_followed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='followed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_followed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
